Initial common contribute rules
ostis-dev/ostis-project pull request #2
Opened 2020-11-02 12:41 UTC by deniskoronchik

2020-11-11 13:08 UTC, deniskoronchik commented on docs/contribute.md
> +- Each repository steup minimal number of reviewers for Pull Requests. But this number can't be less then `1`
```suggestion
- Each repository setup minimal number of reviewers for Pull Requests. But this number can't be less then `1`
```

2020-11-11 13:11 UTC, KovalM requested changes

2020-11-11 13:11 UTC, KovalM commented on docs/contribute.md
> +- Pull Request can be merged before approves by all reviewers
```suggestion
- Pull Request can't be merged before approves by all reviewers
```

2021-02-01 20:48 UTC, KovalM approved these changes

2021-02-02 13:16 UTC, merged